# Generated by Django 3.2.6 on 2021-09-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0014_message_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='slug',
            field=models.SlugField(max_length=120, null=True),
        ),
    ]
