# Generated by Django 3.2.6 on 2021-09-21 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0016_auto_20210920_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='seen',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
