# Generated by Django 3.2.6 on 2021-09-21 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0017_chatroom_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='seen',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
