# Generated by Django 3.2.6 on 2021-09-21 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0018_alter_chatroom_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='seen',
        ),
    ]
